///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AuthModelUser {
/*
{
  "id": "83fb6c2b-80f9-4bbc-9979-3f9eea2a1289",
  "email": "user@example.com",
  "userName": "string",
  "name": "string",
  "gender": "MALE",
  "dob": "2000-01-01T00:00:00.000Z",
  "role": "USER"
}
*/

  String? id;
  String? email;
  String? userName;
  String? name;
  String? gender;
  String? dob;
  String? role;

  AuthModelUser({
    this.id,
    this.email,
    this.userName,
    this.name,
    this.gender,
    this.dob,
    this.role,
  });
  AuthModelUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    email = json['email']?.toString();
    userName = json['userName']?.toString();
    name = json['name']?.toString();
    gender = json['gender']?.toString();
    dob = json['dob']?.toString();
    role = json['role']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['email'] = email;
    data['userName'] = userName;
    data['name'] = name;
    data['gender'] = gender;
    data['dob'] = dob;
    data['role'] = role;
    return data;
  }
}

class AuthModel {
/*
{
  "message": "Unauthorized",
  "statusCode": 401,
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJzdWIiOiI4M2ZiNmMyYi04MGY5LTRiYmMtOTk3OS0zZjllZWEyYTEyODkiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc0OTc5OTQ4NiwiZXhwIjoxNzUwNDA0Mjg2fQ._OxIpRltEuLYNsl0TFeAbrVAIyhvnOwipUqRi5MJvx0",
  "user": {
    "id": "83fb6c2b-80f9-4bbc-9979-3f9eea2a1289",
    "email": "user@example.com",
    "userName": "string",
    "name": "string",
    "gender": "MALE",
    "dob": "2000-01-01T00:00:00.000Z",
    "role": "USER"
  }
}
*/

  String? accessToken;
  AuthModelUser? user;

  AuthModel({
    this.accessToken,
    this.user,
  });
  AuthModel.fromJson(Map<String, dynamic> json) {
    accessToken = json['access_token']?.toString();
    user = (json['user'] != null) ? AuthModelUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['access_token'] = accessToken;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}