///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DailyQuizModelQuestionsOptions {
/*
{
  "id": "0650ebf9-c160-4e6b-adbf-740e8289a3a8",
  "text": "Paris",
  "isCorrect": true
}
*/

  String? id;
  String? text;
  bool? isCorrect;

  DailyQuizModelQuestionsOptions({
    this.id,
    this.text,
    this.isCorrect,
  });
  DailyQuizModelQuestionsOptions.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    text = json['text']?.toString();
    isCorrect = json['isCorrect'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['text'] = text;
    data['isCorrect'] = isCorrect;
    return data;
  }
}

class DailyQuizModelQuestions {
/*
{
  "id": "d640e405-9f5a-4f81-bbdd-a9d4784f7f70",
  "text": "What is the capital of France?",
  "description": "Geography question",
  "options": [
    {
      "id": "0650ebf9-c160-4e6b-adbf-740e8289a3a8",
      "text": "Paris",
      "isCorrect": true
    }
  ]
}
*/

  String? id;
  String? text;
  String? description;
  List<DailyQuizModelQuestionsOptions?>? options;

  DailyQuizModelQuestions({
    this.id,
    this.text,
    this.description,
    this.options,
  });
  DailyQuizModelQuestions.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    text = json['text']?.toString();
    description = json['description']?.toString();
    if (json['options'] != null) {
      final v = json['options'];
      final arr0 = <DailyQuizModelQuestionsOptions>[];
      v.forEach((v) {
        arr0.add(DailyQuizModelQuestionsOptions.fromJson(v));
      });
      options = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['text'] = text;
    data['description'] = description;
    if (options != null) {
      final v = options;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['options'] = arr0;
    }
    return data;
  }
}

class DailyQuizModel {
/*
{
  "id": "7a2b10ae-b5c7-4002-a1f6-6e3901396ee8",
  "title": "sdf",
  "quiz_date": "2025-06-17T00:00:00.000Z",
  "createdById": "1ba5b860-d696-485f-a579-6cd7ae42fb31",
  "questions": [
    {
      "id": "d640e405-9f5a-4f81-bbdd-a9d4784f7f70",
      "text": "What is the capital of France?",
      "description": "Geography question",
      "options": [
        {
          "id": "0650ebf9-c160-4e6b-adbf-740e8289a3a8",
          "text": "Paris",
          "isCorrect": true
        }
      ]
    }
  ]
}
*/

  String? id;
  String? title;
  String? quizDate;
  String? createdById;
  List<DailyQuizModelQuestions?>? questions;

  DailyQuizModel({
    this.id,
    this.title,
    this.quizDate,
    this.createdById,
    this.questions,
  });
  DailyQuizModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    title = json['title']?.toString();
    quizDate = json['quiz_date']?.toString();
    createdById = json['createdById']?.toString();
    if (json['questions'] != null) {
      final v = json['questions'];
      final arr0 = <DailyQuizModelQuestions>[];
      v.forEach((v) {
        arr0.add(DailyQuizModelQuestions.fromJson(v));
      });
      questions = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['quiz_date'] = quizDate;
    data['createdById'] = createdById;
    if (questions != null) {
      final v = questions;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['questions'] = arr0;
    }
    return data;
  }
}
