///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProfileModel {
/*
{
  "id": "28878f93-870a-46d2-b345-3e0c130dfb3d",
  "email": "ahsan@yopmail.com",
  "userName": "ahsansainch",
  "name": "Muhammad Ahsan",
  "gender": null,
  "dob": null,
  "logo": null,
  "authProvider": "NATIVE",
  "createdAt": "2025-06-13T11:57:05.144Z"
}
*/

  String? id;
  String? email;
  String? userName;
  String? name;
  String? gender;
  String? dob;
  String? logo;
  String? authProvider;
  String? createdAt;

  ProfileModel({
    this.id,
    this.email,
    this.userName,
    this.name,
    this.gender,
    this.dob,
    this.logo,
    this.authProvider,
    this.createdAt,
  });
  ProfileModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    email = json['email']?.toString();
    userName = json['userName']?.toString();
    name = json['name']?.toString();
    gender = json['gender']?.toString();
    dob = json['dob']?.toString();
    logo = json['logo']?.toString();
    authProvider = json['authProvider']?.toString();
    createdAt = json['createdAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['email'] = email;
    data['userName'] = userName;
    data['name'] = name;
    data['gender'] = gender;
    data['dob'] = dob;
    data['logo'] = logo;
    data['authProvider'] = authProvider;
    data['createdAt'] = createdAt;
    return data;
  }
}
