///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubmitQuizModelUserAnswers {
/*
{
  "id": "308d9c7a-0a37-40ea-8c4b-5c4e33e433f2",
  "attemptId": "e1b480d4-2cd1-4670-a55a-254bf5289d5f",
  "questionId": "46cb7f0f-8186-4e8a-a963-08390e2fd2bc",
  "optionId": "3de36c0a-32a9-4e7f-8c83-c5da2757a974",
  "isCorrect": false
}
*/

  String? id;
  String? attemptId;
  String? questionId;
  String? optionId;
  bool? isCorrect;

  SubmitQuizModelUserAnswers({
    this.id,
    this.attemptId,
    this.questionId,
    this.optionId,
    this.isCorrect,
  });
  SubmitQuizModelUserAnswers.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    attemptId = json['attemptId']?.toString();
    questionId = json['questionId']?.toString();
    optionId = json['optionId']?.toString();
    isCorrect = json['isCorrect'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['attemptId'] = attemptId;
    data['questionId'] = questionId;
    data['optionId'] = optionId;
    data['isCorrect'] = isCorrect;
    return data;
  }
}

class SubmitQuizModel {
/*
{
  "id": "e1b480d4-2cd1-4670-a55a-254bf5289d5f",
  "userId": "06b58782-cc45-42a3-afef-65e219d59b8b",
  "quizId": "c43c7182-7c75-442b-a80a-4f4f638ddec7",
  "score": 1,
  "completedAt": "2025-06-18T11:12:25.798Z",
  "userAnswers": [
    {
      "id": "308d9c7a-0a37-40ea-8c4b-5c4e33e433f2",
      "attemptId": "e1b480d4-2cd1-4670-a55a-254bf5289d5f",
      "questionId": "46cb7f0f-8186-4e8a-a963-08390e2fd2bc",
      "optionId": "3de36c0a-32a9-4e7f-8c83-c5da2757a974",
      "isCorrect": false
    }
  ]
}
*/

  String? id;
  String? userId;
  String? quizId;
  int? score;
  String? completedAt;
  List<SubmitQuizModelUserAnswers?>? userAnswers;

  SubmitQuizModel({
    this.id,
    this.userId,
    this.quizId,
    this.score,
    this.completedAt,
    this.userAnswers,
  });
  SubmitQuizModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    userId = json['userId']?.toString();
    quizId = json['quizId']?.toString();
    score = json['score']?.toInt();
    completedAt = json['completedAt']?.toString();
    if (json['userAnswers'] != null) {
      final v = json['userAnswers'];
      final arr0 = <SubmitQuizModelUserAnswers>[];
      v.forEach((v) {
        arr0.add(SubmitQuizModelUserAnswers.fromJson(v));
      });
      userAnswers = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['quizId'] = quizId;
    data['score'] = score;
    data['completedAt'] = completedAt;
    if (userAnswers != null) {
      final v = userAnswers;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['userAnswers'] = arr0;
    }
    return data;
  }
}
